/**
 * Load-time JSON for DJ Creator wizard (generated by `npm run dj-creator:import-rules`).
 * Do not read XLSX at runtime — only this bundle.
 */

import type {
  DjCreatorMatchContext,
  DjCreatorRuleRow,
  DjCreatorRulesBundle,
} from "@/lib/recommendations/dj-creator-rules.types";
import bundle from "@/lib/recommendations/dj-creator-rules.generated.json";

const typed = bundle as DjCreatorRulesBundle;

export function getDjCreatorRulesBundle(): DjCreatorRulesBundle {
  return typed;
}

function norm(s: string | undefined | null): string {
  return String(s ?? "")
    .trim()
    .toLowerCase();
}

/**
 * Match one dimension. Rule-side * / any / empty = wildcard.
 * When `allowCtxWildcard`, context * / any / empty = wildcard (used for audience we do not collect).
 */
function fieldMatch(ruleVal: string, ctxVal: string, allowCtxWildcard: boolean): boolean {
  const c = norm(ctxVal);
  if (allowCtxWildcard && (c === "" || c === "*" || c === "any")) return true;
  if (!allowCtxWildcard && c === "") return false;
  const r = norm(ruleVal);
  if (r === "" || r === "*" || r === "any") return true;
  return r === c;
}

const WIZARD_BUSINESS_TO_RULE: Record<string, string> = {
  restaurant: "RESTAURANT",
  cafe: "CAFE",
  hotel: "HOTEL_LOBBY",
  spa: "OTHER",
  gym: "GYM",
  bar: "BAR_NIGHTLIFE",
  other: "OTHER",
};

const WIZARD_VIBE_TO_RULE: Record<string, string> = {
  calm: "calm",
  romantic: "romantic",
  premium: "premium",
  happy: "happy",
  /** Sexy / rhythmic / evening-out — maps to upbeat “happy” rows; client shows house/club style chips. */
  rhythmic: "happy",
  energy: "high_energy",
  "high energy": "high_energy",
};

/** Rule `vibe` value -> typical `energy` axis in the sheet (wizard does not collect audience/energy yet). */
const RULE_VIBE_TO_ENERGY: Record<string, string> = {
  calm: "low",
  romantic: "low_medium",
  premium: "low_medium",
  /** Non-gym happy — match sheet `medium` rows (e.g. RESTAURANT_EVENING_HAPPY); gym remaps happy→high_energy. */
  happy: "medium",
  high_energy: "high",
  balanced: "medium",
};

function mapWizardBusinessId(raw: string): string {
  const k = norm(raw).replace(/\s+/g, "");
  if (k in WIZARD_BUSINESS_TO_RULE) return WIZARD_BUSINESS_TO_RULE[k]!;
  return String(raw ?? "")
    .trim()
    .toUpperCase()
    .replace(/\s+/g, "_");
}

function mapWizardVibeId(raw: string): string {
  const k = norm(raw);
  if (k in WIZARD_VIBE_TO_RULE) return WIZARD_VIBE_TO_RULE[k]!;
  return k.replace(/\s+/g, "_");
}

/** Wizard daypart bubble id → sheet `daypart` column (afternoon slots use lunch rules). */
const WIZARD_DAYPART_TO_RULE_DAYPART: Record<string, string> = {
  morning: "morning",
  lunch: "lunch",
  afternoon: "lunch",
  evening: "evening",
  night: "night",
};

/**
 * Evening is ambiguous: refined dinner moods use `dinner` rows; upbeat evening-out uses `evening` rows.
 */
export function mapWizardDaypartForRuleDaypart(daypartId: string, vibeId: string): string {
  const k = norm(daypartId);
  const v = norm(vibeId);
  if (k === "evening") {
    if (v === "happy" || v === "energy" || v === "rhythmic" || v === "high_energy") return "evening";
    return "dinner";
  }
  return WIZARD_DAYPART_TO_RULE_DAYPART[k] ?? k;
}

function energyFromRuleVibe(ruleVibe: string): string {
  const key = norm(ruleVibe).replace(/\s+/g, "_");
  return RULE_VIBE_TO_ENERGY[key] ?? "medium";
}

/**
 * Maps JONNY wizard bubble ids to the enum strings used in `DJ_Creator_Rules`.
 * Returns null until business, daypart, and vibe are all chosen.
 */
export function buildDjCreatorMatchContextFromWizard(picks: {
  businessId: string;
  daypartId: string;
  vibeId: string;
}): DjCreatorMatchContext | null {
  const b = String(picks.businessId ?? "").trim();
  const d = String(picks.daypartId ?? "").trim();
  const v = String(picks.vibeId ?? "").trim();
  if (!b || !d || !v) return null;

  const businessType = mapWizardBusinessId(b);
  let daypart = mapWizardDaypartForRuleDaypart(d, v);
  let vibe = mapWizardVibeId(v);
  let energy = energyFromRuleVibe(vibe);

  /* Gym: “happy” in a gym is treated as high-energy for rule matching (sheet rows use high_energy + high). */
  if (norm(businessType) === "gym") {
    if (norm(vibe) === "happy" || norm(v) === "rhythmic") {
      vibe = "high_energy";
      energy = "high";
    }
    /* No GYM_NIGHT rule yet — night uses the same playbook as evening. */
    if (norm(daypart) === "night") {
      daypart = "evening";
    }
  }

  return {
    businessType,
    daypart,
    vibe,
    energy,
    audience: "*",
  };
}

/**
 * Active rules: lower `priority` wins (1 before 50). Ties keep sheet order.
 */
export function matchDjCreatorRule(ctx: DjCreatorMatchContext): DjCreatorRuleRow | null {
  const rules = typed.rules.filter((r) => r.isActive);
  const sorted = [...rules].sort((a, b) => a.priority - b.priority);
  for (const r of sorted) {
    if (!fieldMatch(r.businessType, ctx.businessType, false)) continue;
    if (!fieldMatch(r.daypart, ctx.daypart, false)) continue;
    if (!fieldMatch(r.vibe, ctx.vibe, false)) continue;
    if (!fieldMatch(r.energy, ctx.energy ?? "", false)) continue;
    if (!fieldMatch(r.audience, ctx.audience ?? "", true)) continue;
    return r;
  }
  /* Never fall back to generic calm styles for gym high-energy intent. */
  if (norm(ctx.businessType) === "gym" && norm(ctx.vibe) === "high_energy") {
    return fallbackGymHighEnergyRule(ctx);
  }
  return null;
}

function fallbackGymHighEnergyRule(ctx: DjCreatorMatchContext): DjCreatorRuleRow | null {
  const pool = typed.rules.filter(
    (r) => r.isActive && norm(r.businessType) === "gym" && norm(r.vibe) === "high_energy",
  );
  if (pool.length === 0) return null;
  const d = norm(ctx.daypart);
  const dayMatches = pool.filter((r) => norm(r.daypart) === d);
  const narrowed = dayMatches.length > 0 ? dayMatches : pool;
  const e = norm(ctx.energy ?? "");
  const energyMatches = narrowed.filter((r) => norm(r.energy) === e);
  const narrowed2 = energyMatches.length > 0 ? energyMatches : narrowed;
  return [...narrowed2].sort((a, b) => a.priority - b.priority)[0] ?? null;
}

/** Wizard selection: gym + upbeat / peak-energy vibes use the high-energy gym path (styles + final step). */
export function isGymHighEnergyWizardVibes(businessId: string, vibeId: string): boolean {
  if (norm(mapWizardBusinessId(businessId)) !== "gym") return false;
  const v = norm(vibeId);
  return v === "happy" || v === "energy" || v === "rhythmic";
}

export function effectiveResultCount(rule: DjCreatorRuleRow | null, fallback: number): number {
  const n = rule?.resultCountDefault;
  if (n == null || !Number.isFinite(n)) return fallback;
  return Math.min(50, Math.max(1, Math.floor(n)));
}
