/**
 * Infer music genre from title or search query.
 * Used when adding playlists/sources so they don't all show "Mixed".
 */

/** Keywords -> display genre. Longest matches first for specificity. */
const GENRE_KEYWORDS: [string, string][] = [
  // Hebrew
  ["אפרוביט", "Afrobeat"],
  ["אפרו", "Afrobeat"],
  ["אפריקאי", "Afro"],
  ["מזרחי", "Mizrahi"],
  ["ים תיכוני", "Mediterranean"],
  ["טראנס", "Trance"],
  ["האוס", "House"],
  ["טכנו", "Techno"],
  ["רגאיי", "Reggae"],
  ["דאבסטפ", "Dubstep"],
  ["פופ", "Pop"],
  ["רוק", "Rock"],
  ["היפ הופ", "Hip Hop"],
  ["רית'ם אנד בלוז", "R&B"],
  ["ג'אז", "Jazz"],
  ["בלוז", "Blues"],
  ["קלאסי", "Classical"],
  ["אלקטרוני", "Electronic"],
  ["דאנס", "Dance"],
  ["עממי", "Folk"],
  ["מטאל", "Metal"],
  ["פאנק", "Punk"],
  ["סול", "Soul"],
  ["דיסקו", "Disco"],
  ["אמביינט", "Ambient"],
  ["דרים", "Dream"],
  ["סינת'פופ", "Synth Pop"],
  ["אינדי", "Indie"],
  ["אלטרנטיבי", "Alternative"],
  ["ישראלי", "Israeli"],
  ["עברי", "Hebrew"],
  ["ערבי", "Arabic"],
  ["בלקן", "Balkan"],
  ["יווני", "Greek"],
  ["טורקי", "Turkish"],
  // English
  ["afrobeat", "Afrobeat"],
  ["afro beat", "Afrobeat"],
  ["afro", "Afro"],
  ["mizrahi", "Mizrahi"],
  ["mediterranean", "Mediterranean"],
  ["trance", "Trance"],
  ["house", "House"],
  ["techno", "Techno"],
  ["reggae", "Reggae"],
  ["dubstep", "Dubstep"],
  ["drum and bass", "Drum & Bass"],
  ["drum n bass", "Drum & Bass"],
  ["dnb", "Drum & Bass"],
  ["edm", "EDM"],
  ["chill", "Chill"],
  ["chillout", "Chill"],
  ["lofi", "Lofi"],
  ["lo-fi", "Lofi"],
  ["lofi hip hop", "Lofi"],
  ["jazz", "Jazz"],
  ["blues", "Blues"],
  ["classical", "Classical"],
  ["electronic", "Electronic"],
  ["dance", "Dance"],
  ["folk", "Folk"],
  ["metal", "Metal"],
  ["punk", "Punk"],
  ["soul", "Soul"],
  ["disco", "Disco"],
  ["ambient", "Ambient"],
  ["dream pop", "Dream Pop"],
  ["synth pop", "Synth Pop"],
  ["indie", "Indie"],
  ["alternative", "Alternative"],
  ["pop", "Pop"],
  ["rock", "Rock"],
  ["hip hop", "Hip Hop"],
  ["hip-hop", "Hip Hop"],
  ["rap", "Rap"],
  ["r&b", "R&B"],
  ["rnb", "R&B"],
  ["latin", "Latin"],
  ["salsa", "Salsa"],
  ["bachata", "Bachata"],
  ["reggaeton", "Reggaeton"],
  ["kizomba", "Kizomba"],
  ["samba", "Samba"],
  ["bossa nova", "Bossa Nova"],
  ["flamenco", "Flamenco"],
  ["gospel", "Gospel"],
  ["country", "Country"],
  ["funk", "Funk"],
  ["psytrance", "Psytrance"],
  ["psy trance", "Psytrance"],
  ["progressive", "Progressive"],
  ["deep house", "Deep House"],
  ["tech house", "Tech House"],
  ["minimal", "Minimal"],
  ["hardstyle", "Hardstyle"],
  ["hardcore", "Hardcore"],
  ["trap", "Trap"],
  ["drill", "Drill"],
  ["grime", "Grime"],
  ["uk garage", "UK Garage"],
  ["breakbeat", "Breakbeat"],
  ["downtempo", "Downtempo"],
  ["trip hop", "Trip Hop"],
  ["idm", "IDM"],
  ["experimental", "Experimental"],
  ["world music", "World"],
  ["world", "World"],
  ["israeli", "Israeli"],
  ["hebrew", "Hebrew"],
  ["arabic", "Arabic"],
  ["balkan", "Balkan"],
  ["greek", "Greek"],
  ["turkish", "Turkish"],
  ["live set", "Live"],
  ["dj set", "DJ Set"],
  ["mix", "Mix"],
  ["remix", "Remix"],
  ["cover", "Cover"],
  ["acoustic", "Acoustic"],
  ["unplugged", "Acoustic"],
  ["karaoke", "Karaoke"],
  ["instrumental", "Instrumental"],
  ["vocal", "Vocal"],
  ["top hits", "Pop"],
  ["hits", "Pop"],
  ["greatest hits", "Pop"],
  ["best of", "Pop"],
];

// Sort by keyword length descending so "afro beat" matches before "afro"
const SORTED = [...GENRE_KEYWORDS].sort((a, b) => b[0].length - a[0].length);

/**
 * Infer genre from title and optional search query.
 * Returns "Mixed" if no genre keyword is found.
 */
export function inferGenre(title: string, query = ""): string {
  const text = `${title} ${query}`.toLowerCase().trim();
  if (!text) return "Mixed";

  for (const [kw, genre] of SORTED) {
    if (text.includes(kw.toLowerCase())) return genre;
  }

  return "Mixed";
}
