import type { Announcement, Branch, Device, LogEntry, Schedule, Source } from "./types";

export const branches: Omit<Branch, "accountId">[] = [
  {
    id: "bldn-001",
    name: "Downtown Flagship",
    code: "DT-FL",
    timezone: "America/New_York",
    city: "New York",
    country: "US",
    status: "active",
    devicesOnline: 7,
    devicesTotal: 8,
  },
  {
    id: "bldn-002",
    name: "Uptown Showroom",
    code: "UP-SR",
    timezone: "America/New_York",
    city: "New York",
    country: "US",
    status: "active",
    devicesOnline: 3,
    devicesTotal: 3,
  },
  {
    id: "bldn-003",
    name: "Riverfront Outlet",
    code: "RF-OT",
    timezone: "America/Chicago",
    city: "Chicago",
    country: "US",
    status: "inactive",
    devicesOnline: 0,
    devicesTotal: 2,
  },
];

export const devices: Omit<Device, "accountId">[] = [
  {
    id: "dev-001",
    name: "Lobby Audio Player",
    branchId: "bldn-001",
    type: "audio-player",
    platform: "windows",
    status: "online",
    health: "ok",
    capabilities: ["supportsPlay", "supportsStop", "supportsVolume", "supportsResume"],
    lastHeartbeat: "2026-03-08T11:31:00Z",
    ipAddress: "10.0.10.21",
    agentVersion: "1.3.2",
    lastSeen: "2026-03-08T11:31:00Z",
    currentSourceId: "src-lofi-stream",
    volume: 68,
  },
  {
    id: "dev-002",
    name: "Showroom Screens",
    branchId: "bldn-001",
    type: "screen-player",
    platform: "windows",
    status: "online",
    health: "ok",
    capabilities: ["supportsPlay", "supportsStop", "supportsResume"],
    lastHeartbeat: "2026-03-08T11:29:00Z",
    ipAddress: "10.0.10.34",
    agentVersion: "1.3.2",
    lastSeen: "2026-03-08T11:29:00Z",
    currentSourceId: "src-spring-campaign",
    volume: 0,
  },
  {
    id: "dev-003",
    name: "In‑Store Announcer",
    branchId: "bldn-001",
    type: "announcement-node",
    platform: "windows",
    status: "online",
    health: "ok",
    capabilities: ["supportsPlay", "supportsStop", "supportsVolume", "supportsResume"],
    lastHeartbeat: "2026-03-08T11:27:00Z",
    ipAddress: "10.0.10.41",
    agentVersion: "1.3.2",
    lastSeen: "2026-03-08T11:27:00Z",
    volume: 62,
  },
  {
    id: "dev-004",
    name: "Uptown Audio Player",
    branchId: "bldn-002",
    type: "audio-player",
    platform: "android",
    status: "maintenance",
    health: "degraded",
    capabilities: ["supportsPlay", "supportsStop", "supportsVolume", "supportsResume"],
    lastHeartbeat: "2026-03-08T10:58:00Z",
    ipAddress: "10.0.20.15",
    agentVersion: "1.2.9",
    lastSeen: "2026-03-08T10:58:00Z",
    currentSourceId: "src-brand-bed",
    volume: 55,
  },
  {
    id: "dev-005",
    name: "Riverfront Audio Player",
    branchId: "bldn-003",
    type: "audio-player",
    platform: "windows",
    status: "offline",
    health: "error",
    capabilities: ["supportsPlay", "supportsStop", "supportsVolume"],
    lastHeartbeat: "2026-03-07T21:12:00Z",
    ipAddress: "10.0.30.10",
    agentVersion: "1.2.3",
    lastSeen: "2026-03-07T21:12:00Z",
    volume: 0,
  },
];

/** Playback targets. SyncBiz does NOT store media – only metadata and control instructions. */
export const sources: Omit<Source, "accountId">[] = [
  {
    id: "src-lofi-stream",
    name: "In‑Store Lofi Stream",
    type: "stream_url",
    target: "https://customer-stream.example.com/lofi",
    branchId: "bldn-001",
    description: "Customer-provided stream for ambient background.",
    capabilities: ["play", "stop", "volume"],
    isLive: true,
    tags: ["ambient", "weekday"],
  },
  {
    id: "src-spring-campaign",
    name: "Spring Campaign Loop",
    type: "playlist_url",
    target: "https://media.internal.example.com/playlists/spring-2026",
    branchId: "bldn-001",
    description: "Customer-owned playlist for seasonal campaign.",
    capabilities: ["play", "stop", "resume"],
    isLive: true,
    tags: ["promo"],
  },
  {
    id: "src-local-folder",
    name: "Local Store Library",
    type: "app_target",
    target: "D:/Media/StoreLibrary",
    branchId: "bldn-001",
    description: "Local path on device – customer-owned content.",
    capabilities: ["play", "stop", "resume"],
    isLive: false,
    tags: ["fallback"],
  },
  {
    id: "src-brand-bed",
    name: "Brand Audio Bed",
    type: "app_target",
    target: "D:/Media/Brand/bed.wav",
    branchId: "bldn-001",
    description: "Short bed used under TTS.",
    capabilities: ["play", "stop"],
    isLive: false,
  },
  {
    id: "src-store-playlist",
    name: "Store Playlist",
    type: "local_playlist",
    target: "D:\\APP Project\\Playlists\\afro.m3u",
    branchId: "bldn-001",
    description: "Local playlist on endpoint — agent launches with default player.",
    capabilities: ["play", "stop"],
    isLive: false,
  },
  {
    id: "src-tts-template",
    name: "Generic TTS",
    type: "tts",
    target: "tts://template",
    branchId: "bldn-001",
    description: "TTS message template.",
    capabilities: ["play", "stop", "resume"],
    isLive: false,
  },
  {
    id: "src-youtube-demo",
    name: "Lofi Beats Radio",
    type: "stream_url",
    target: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    branchId: "bldn-001",
    description: "Embedded YouTube stream for ambient playback.",
    capabilities: ["play", "pause", "stop", "volume"],
    isLive: true,
    provider: "youtube",
    playerMode: "embedded",
  },
  {
    id: "src-soundcloud-demo",
    name: "SoundCloud Track",
    type: "stream_url",
    target: "https://soundcloud.com/lofigeek/lofi-chill-mix",
    branchId: "bldn-001",
    description: "Embedded SoundCloud track.",
    capabilities: ["play", "pause", "stop", "volume", "seek"],
    isLive: false,
    provider: "soundcloud",
    playerMode: "embedded",
  },
];

export const schedules: Omit<Schedule, "accountId">[] = [
  {
    id: "sch-weekday-morning",
    name: "Weekday Morning",
    branchId: "bldn-001",
    targetType: "SOURCE",
    targetId: "src-local-folder",
    deviceId: "dev-001",
    sourceId: "src-local-folder",
    daysOfWeek: [1, 2, 3, 4, 5],
    startTimeLocal: "08:00",
    endTimeLocal: "11:00",
    enabled: true,
    priority: 5,
  },
  {
    id: "sch-campaign-loop",
    name: "Spring Campaign",
    branchId: "bldn-001",
    targetType: "SOURCE",
    targetId: "src-spring-campaign",
    deviceId: "dev-002",
    sourceId: "src-spring-campaign",
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startTimeLocal: "09:00",
    endTimeLocal: "21:00",
    enabled: true,
    priority: 8,
  },
  {
    id: "sch-uptown-default",
    name: "Uptown Default",
    branchId: "bldn-002",
    targetType: "SOURCE",
    targetId: "src-lofi-stream",
    deviceId: "dev-004",
    sourceId: "src-lofi-stream",
    daysOfWeek: [1, 2, 3, 4, 5],
    startTimeLocal: "10:00",
    endTimeLocal: "18:00",
    enabled: false,
    priority: 3,
  },
];

export const announcements: Omit<Announcement, "accountId">[] = [
  {
    id: "ann-loyalty-push",
    title: "Loyalty Program Reminder",
    message: "Remind customers about the new loyalty program and double points this week.",
    branchId: "bldn-001",
    type: "tts",
    scheduleId: "sch-weekday-morning",
    status: "scheduled",
    priority: "normal",
    ttsEnabled: true,
    resumePreviousSource: true,
    windowStart: "2026-03-08T13:00:00Z",
    windowEnd: "2026-03-08T17:00:00Z",
  },
  {
    id: "ann-uptown-event",
    title: "Uptown Live Event",
    message: "Announce the in‑store demo event starting at 6pm.",
    branchId: "bldn-002",
    type: "announcement_trigger",
    status: "draft",
    priority: "high",
    ttsEnabled: false,
    resumePreviousSource: true,
    windowStart: "2026-03-09T21:30:00Z",
    windowEnd: "2026-03-09T23:00:00Z",
  },
];

export const logs: Omit<LogEntry, "accountId">[] = [
  {
    id: "log-001",
    timestamp: "2026-03-08T11:31:12Z",
    level: "info",
    message: "Device heartbeat received from Lobby Audio Player.",
    branchId: "bldn-001",
    deviceId: "dev-001",
  },
  {
    id: "log-002",
    timestamp: "2026-03-08T11:30:01Z",
    level: "warning",
    message: "Stream buffer underrun; endpoint switched to local fallback.",
    branchId: "bldn-001",
    deviceId: "dev-001",
    sourceId: "src-lofi-stream",
  },
  {
    id: "log-003",
    timestamp: "2026-03-08T11:25:10Z",
    level: "info",
    message: "Schedule executed: Spring Campaign on Showroom Screens.",
    branchId: "bldn-001",
    deviceId: "dev-002",
    sourceId: "src-spring-campaign",
    scheduleId: "sch-campaign-loop",
  },
  {
    id: "log-004",
    timestamp: "2026-03-08T10:59:40Z",
    level: "warning",
    message: "Agent update pending on Uptown Audio Player.",
    branchId: "bldn-002",
    deviceId: "dev-004",
  },
  {
    id: "log-005",
    timestamp: "2026-03-08T09:15:03Z",
    level: "error",
    message: "Riverfront Audio Player offline for more than 12 hours.",
    branchId: "bldn-003",
    deviceId: "dev-005",
  },
  {
    id: "log-006",
    timestamp: "2026-03-08T08:02:10Z",
    level: "info",
    message: "Weekday Morning schedule executed.",
    branchId: "bldn-001",
    deviceId: "dev-001",
    scheduleId: "sch-weekday-morning",
  },
];
