import type { MusicTaxonomySeedRow } from "@/lib/music-taxonomy-types";

/**
 * Fallback starter vocabulary when no `prisma/seed-data/music-taxonomy.generated.json`
 * is present (see docs). Import the official Excel via `npm run music-taxonomy:import-xlsx`
 * to replace this with the canonical sheet “Stage 3 Seed”.
 */
export const DEFAULT_MUSIC_TAXONOMY_SEED_ROWS: MusicTaxonomySeedRow[] = [
  // PLAYBACK_CONTEXT
  {
    slug: "playback-context-foreground",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Foreground",
    labelHe: "חזית מוזיקלי",
    descriptionHeUser: "מוזיקה במרכז תשומת הלב; בולטת ללקוחות.",
    sortOrder: 10,
    aliases: ["fg", "front-and-center"],
  },
  {
    slug: "playback-context-background",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Background",
    labelHe: "רקע",
    descriptionHeUser: "מוזיקת רקע שאינה מושכת תשומת לב יתרה.",
    sortOrder: 20,
    aliases: ["bg"],
  },
  {
    slug: "playback-context-dinner-service",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Dinner service",
    labelHe: "שירות ארוחת ערב",
    sortOrder: 30,
  },
  {
    slug: "playback-context-lounge-seating",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Lounge seating",
    labelHe: "אזור ישיבה / לאונג'",
    sortOrder: 40,
  },
  {
    slug: "playback-context-retail-floor",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Retail floor",
    labelHe: "רצפת מכירות",
    sortOrder: 50,
  },
  {
    slug: "playback-context-gym-floor",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Gym floor",
    labelHe: "אזור אימון",
    sortOrder: 60,
  },
  {
    slug: "playback-context-spa-quiet",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Spa / treatment (quiet)",
    labelHe: "ספא / טיפולים (שקט)",
    sortOrder: 70,
  },
  {
    slug: "playback-context-lobby-welcome",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Lobby / welcome",
    labelHe: "לובי / קבלת פנים",
    sortOrder: 80,
  },
  {
    slug: "playback-context-outdoor-terrace",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Outdoor / terrace",
    labelHe: "חוץ / מרפסת",
    sortOrder: 90,
  },
  {
    slug: "playback-context-queue-holding",
    category: "PLAYBACK_CONTEXT",
    labelEn: "Queue / holding area",
    labelHe: "תור / אזור המתנה",
    sortOrder: 100,
  },
  // VIBE_ENERGY
  {
    slug: "vibe-energy-low",
    category: "VIBE_ENERGY",
    labelEn: "Low energy",
    labelHe: "אנרגיה נמוכה",
    sortOrder: 10,
    aliases: ["calm"],
  },
  {
    slug: "vibe-energy-medium-low",
    category: "VIBE_ENERGY",
    labelEn: "Medium-low energy",
    labelHe: "אנרגיה בינונית־נמוכה",
    sortOrder: 20,
  },
  {
    slug: "vibe-energy-medium",
    category: "VIBE_ENERGY",
    labelEn: "Medium energy",
    labelHe: "אנרגיה בינונית",
    sortOrder: 30,
  },
  {
    slug: "vibe-energy-medium-high",
    category: "VIBE_ENERGY",
    labelEn: "Medium-high energy",
    labelHe: "אנרגיה בינונית־גבוהה",
    sortOrder: 40,
  },
  {
    slug: "vibe-energy-high",
    category: "VIBE_ENERGY",
    labelEn: "High energy",
    labelHe: "אנרגיה גבוהה",
    sortOrder: 50,
  },
  {
    slug: "vibe-energy-peak",
    category: "VIBE_ENERGY",
    labelEn: "Peak / anthem",
    labelHe: "שיא / הפוגה רועמת",
    sortOrder: 60,
  },
  // MAIN_SOUND_GENRE
  {
    slug: "genre-pop",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Pop",
    labelHe: "פופ",
    sortOrder: 10,
  },
  {
    slug: "genre-rock",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Rock",
    labelHe: "רוק",
    sortOrder: 20,
  },
  {
    slug: "genre-alt-rock",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Alternative rock",
    labelHe: "רוק אלטרנטיבי",
    sortOrder: 25,
    status: "MERGED",
    mergedIntoSlug: "genre-rock",
  },
  {
    slug: "genre-hip-hop",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Hip-hop",
    labelHe: "היפ הופ",
    sortOrder: 30,
  },
  {
    slug: "genre-electronic",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Electronic",
    labelHe: "אלקטרוני",
    sortOrder: 40,
  },
  {
    slug: "genre-jazz",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Jazz",
    labelHe: "ג׳אז",
    sortOrder: 50,
  },
  {
    slug: "genre-classical",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Classical",
    labelHe: "קלאסי",
    sortOrder: 60,
  },
  {
    slug: "genre-latin",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Latin",
    labelHe: "לטיני",
    sortOrder: 70,
  },
  {
    slug: "genre-soul-funk",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Soul / Funk",
    labelHe: "סול / פאנק",
    sortOrder: 80,
  },
  {
    slug: "genre-country",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Country / Americana",
    labelHe: "קאנטרי / אמריקנה",
    sortOrder: 90,
  },
  {
    slug: "genre-world",
    category: "MAIN_SOUND_GENRE",
    labelEn: "World",
    labelHe: "עולמי",
    sortOrder: 100,
  },
  {
    slug: "genre-reggae",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Reggae / Dub",
    labelHe: "רגאיי / דאב",
    sortOrder: 110,
  },
  {
    slug: "genre-metal",
    category: "MAIN_SOUND_GENRE",
    labelEn: "Metal",
    labelHe: "מטאל",
    sortOrder: 120,
  },
  // STYLE_TAGS
  {
    slug: "style-acoustic",
    category: "STYLE_TAGS",
    labelEn: "Acoustic-led",
    labelHe: "אקוסטי מוביל",
    sortOrder: 10,
  },
  {
    slug: "style-vocal-forward",
    category: "STYLE_TAGS",
    labelEn: "Vocal-forward",
    labelHe: "קול במרכז",
    sortOrder: 20,
  },
  {
    slug: "style-instrumental-forward",
    category: "STYLE_TAGS",
    labelEn: "Instrumental-forward",
    labelHe: "כלי נגינה במרכז",
    sortOrder: 30,
  },
  {
    slug: "style-live-recording-aesthetic",
    category: "STYLE_TAGS",
    labelEn: "Live recording aesthetic",
    labelHe: "אסתטיקת הופעה חיה",
    sortOrder: 40,
  },
  {
    slug: "style-remix-mashup",
    category: "STYLE_TAGS",
    labelEn: "Remix / mashup",
    labelHe: "רמיקס / מאשאפ",
    sortOrder: 50,
  },
  {
    slug: "style-vintage-era",
    category: "STYLE_TAGS",
    labelEn: "Vintage era",
    labelHe: "תקופה וינטג׳",
    sortOrder: 60,
  },
  {
    slug: "style-modern-current",
    category: "STYLE_TAGS",
    labelEn: "Modern / current",
    labelHe: "מודרני / עדכני",
    sortOrder: 70,
  },
  {
    slug: "style-cinematic",
    category: "STYLE_TAGS",
    labelEn: "Cinematic",
    labelHe: "קולנועי",
    sortOrder: 80,
  },
  {
    slug: "style-minimal",
    category: "STYLE_TAGS",
    labelEn: "Minimal arrangement",
    labelHe: "עיבוד מינימליסטי",
    sortOrder: 90,
  },
  {
    slug: "style-maximal",
    category: "STYLE_TAGS",
    labelEn: "Maximal arrangement",
    labelHe: "עיבוד עשיר",
    sortOrder: 100,
  },
  {
    slug: "style-electronic-edm",
    category: "STYLE_TAGS",
    labelEn: "EDM-forward",
    labelHe: "במבייס איתן",
    sortOrder: 110,
    aliases: ["edm"],
  },
  {
    slug: "style-electronic-deep-house",
    category: "STYLE_TAGS",
    labelEn: "Deep house flavour",
    labelHe: "עומק האוס",
    sortOrder: 120,
    parentSlug: "genre-electronic",
  },
  {
    slug: "style-percussion-forward",
    category: "STYLE_TAGS",
    labelEn: "Percussion-forward",
    labelHe: "כלי הקש במוקד",
    sortOrder: 130,
  },
  // ISRAELI_SPECIALS
  {
    slug: "il-mizrahit",
    category: "ISRAELI_SPECIALS",
    labelEn: "Mizrahit",
    labelHe: "מוזיקה מזרחית",
    sortOrder: 10,
  },
  {
    slug: "il-israeli-pop",
    category: "ISRAELI_SPECIALS",
    labelEn: "Israeli pop",
    labelHe: "פופ ישראלי",
    sortOrder: 20,
  },
  {
    slug: "il-traditional-hebrew-song",
    category: "ISRAELI_SPECIALS",
    labelEn: "Traditional / Hebrew song",
    labelHe: "שיר עברי מסורתי",
    sortOrder: 30,
  },
  {
    slug: "il-hebrew-lyrics-only",
    category: "ISRAELI_SPECIALS",
    labelEn: "Hebrew lyrics only",
    labelHe: "עברית בלבד (מילים)",
    sortOrder: 40,
  },
  {
    slug: "il-memorial-day-somber",
    category: "ISRAELI_SPECIALS",
    labelEn: "Memorial tone (Israel)",
    labelHe: "טון יום זיכרון",
    sortOrder: 50,
  },
  {
    slug: "il-independence-day-celebratory",
    category: "ISRAELI_SPECIALS",
    labelEn: "Independence tone (Israel)",
    labelHe: "טון יום העצמאות",
    sortOrder: 60,
  },
  {
    slug: "il-shabbat-appropriate",
    category: "ISRAELI_SPECIALS",
    labelEn: "Shabbat-appropriate tone",
    labelHe: "מתאים לשבת (תרבותי)",
    sortOrder: 70,
  },
  {
    slug: "il-holiday-chag-general",
    category: "ISRAELI_SPECIALS",
    labelEn: "Jewish holiday — general",
    labelHe: "חג — כללי",
    sortOrder: 80,
  },
  {
    slug: "il-mixed-languages-radio",
    category: "ISRAELI_SPECIALS",
    labelEn: "Mixed languages (IL radio style)",
    labelHe: "שפות מעורבות (סגנון רדיו ישראלי)",
    sortOrder: 90,
  },
  // TECHNICAL_TAGS
  {
    slug: "tech-explicit-lyrics",
    category: "TECHNICAL_TAGS",
    labelEn: "Explicit lyrics",
    labelHe: "מילים גסות / מבוגרות",
    sortOrder: 10,
    aliases: ["explicit"],
  },
  {
    slug: "tech-clean-edit",
    category: "TECHNICAL_TAGS",
    labelEn: "Clean / radio edit",
    labelHe: "גרסת רדיו נקייה",
    sortOrder: 20,
  },
  {
    slug: "tech-instrumental-only",
    category: "TECHNICAL_TAGS",
    labelEn: "Instrumental only",
    labelHe: "אינסטרומנטלי בלבד",
    sortOrder: 30,
  },
  {
    slug: "tech-live-recording",
    category: "TECHNICAL_TAGS",
    labelEn: "Live recording (metadata)",
    labelHe: "הקלטה חיה (מטא)",
    sortOrder: 40,
  },
  {
    slug: "tech-studio-recording",
    category: "TECHNICAL_TAGS",
    labelEn: "Studio recording (metadata)",
    labelHe: "אולפן (מטא)",
    sortOrder: 50,
  },
  {
    slug: "tech-short-duration",
    category: "TECHNICAL_TAGS",
    labelEn: "Short form (≤3 min)",
    labelHe: "קצר (≤3 דק׳)",
    sortOrder: 60,
  },
  {
    slug: "tech-long-form",
    category: "TECHNICAL_TAGS",
    labelEn: "Long form (>5 min)",
    labelHe: "ארוך (>5 דק׳)",
    sortOrder: 70,
  },
  {
    slug: "tech-remaster-flag",
    category: "TECHNICAL_TAGS",
    labelEn: "Remaster (metadata)",
    labelHe: "רמאסטר (מטא)",
    sortOrder: 80,
  },
  // BUSINESS_FIT
  {
    slug: "biz-upscale-dining",
    category: "BUSINESS_FIT",
    labelEn: "Upscale dining",
    labelHe: "מסעדה יוקרתית",
    sortOrder: 10,
  },
  {
    slug: "biz-casual-dining",
    category: "BUSINESS_FIT",
    labelEn: "Casual dining",
    labelHe: "מסעדה קז'ואל",
    sortOrder: 20,
  },
  {
    slug: "biz-fast-casual",
    category: "BUSINESS_FIT",
    labelEn: "Fast casual",
    labelHe: "פאסט־קז'ואל",
    sortOrder: 30,
  },
  {
    slug: "biz-cafe-work",
    category: "BUSINESS_FIT",
    labelEn: "Café / laptop work",
    labelHe: "בית קפה / עבודה עם לפטופ",
    sortOrder: 40,
  },
  {
    slug: "biz-gym-energy",
    category: "BUSINESS_FIT",
    labelEn: "Gym / studio",
    labelHe: "חדר כושר / סטודיו",
    sortOrder: 50,
  },
  {
    slug: "biz-spa-wellness",
    category: "BUSINESS_FIT",
    labelEn: "Spa / wellness",
    labelHe: "ספא / וולנס",
    sortOrder: 60,
  },
  {
    slug: "biz-retail-upbeat",
    category: "BUSINESS_FIT",
    labelEn: "Retail upbeat",
    labelHe: "קמעונאות קצבית",
    sortOrder: 70,
  },
  {
    slug: "biz-hotel-lobby",
    category: "BUSINESS_FIT",
    labelEn: "Hotel lobby",
    labelHe: "לובי מלון",
    sortOrder: 80,
  },
  {
    slug: "biz-bar-nightclub",
    category: "BUSINESS_FIT",
    labelEn: "Bar / nightclub",
    labelHe: "בר / מועדון",
    sortOrder: 90,
  },
  {
    slug: "biz-office-neutral",
    category: "BUSINESS_FIT",
    labelEn: "Office neutral",
    labelHe: "משרד נייטרלי",
    sortOrder: 100,
  },
  // DAYPART_FIT
  {
    slug: "day-breakfast",
    category: "DAYPART_FIT",
    labelEn: "Breakfast",
    labelHe: "ארוחת בוקר",
    sortOrder: 10,
  },
  {
    slug: "day-brunch",
    category: "DAYPART_FIT",
    labelEn: "Brunch",
    labelHe: "בראנץ׳",
    sortOrder: 20,
  },
  {
    slug: "day-lunch",
    category: "DAYPART_FIT",
    labelEn: "Lunch",
    labelHe: "ארוחת צהריים",
    sortOrder: 30,
  },
  {
    slug: "day-afternoon",
    category: "DAYPART_FIT",
    labelEn: "Afternoon",
    labelHe: "אחר הצהריים",
    sortOrder: 40,
  },
  {
    slug: "day-happy-hour",
    category: "DAYPART_FIT",
    labelEn: "Happy hour",
    labelHe: "האפי האוור",
    sortOrder: 50,
  },
  {
    slug: "day-dinner",
    category: "DAYPART_FIT",
    labelEn: "Dinner",
    labelHe: "ארוחת ערב",
    sortOrder: 60,
  },
  {
    slug: "day-late-night",
    category: "DAYPART_FIT",
    labelEn: "Late night",
    labelHe: "סוף לילה",
    sortOrder: 70,
  },
  {
    slug: "day-overnight",
    category: "DAYPART_FIT",
    labelEn: "Overnight",
    labelHe: "משמרת לילה",
    sortOrder: 80,
  },
  {
    slug: "day-opening-closing",
    category: "DAYPART_FIT",
    labelEn: "Opening / closing hours",
    labelHe: "פתיחה / סגירה",
    sortOrder: 90,
  },
  // CATALOG_PROGRAMMING — editorial / programming signals (not genres)
  {
    slug: "selected",
    category: "CATALOG_PROGRAMMING",
    labelEn: "Selected",
    labelHe: "נבחר",
    descriptionHeUser: "נבחר ידנית על ידי SyncBiz / מומלץ לשימוש",
    sortOrder: 10,
    aliases: ["syncbiz-selected", "syncbiz selected", "recommended", "מומלץ", "נבחר"],
  },
  {
    slug: "hits",
    category: "CATALOG_PROGRAMMING",
    labelEn: "Hits",
    labelHe: "להיטים",
    descriptionHeUser: "תוכן מוכר, קליט או להיט שמתאים לקהל רחב",
    sortOrder: 20,
    aliases: ["hit", "hits", "popular", "familiar", "crowd-pleaser", "crowd pleaser", "להיט", "להיטים"],
  },
];
